/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import Control.ClientControl;
import Control.Command;
import java.net.Socket;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Status;
import model.Stringsend;
import model.ThreeCard;
import model.User;
import model.serverSendObject;
import model.userSendObject;

/**
 *
 * @author van hieu
 */
public class RoomView extends javax.swing.JFrame {

    /**
     * Creates new form RoomView
     */
    public User o;
    public ClientControl cl;
    public boolean c;
    Thread thread;
    String s[];
    Status sta1[];
    boolean check;
    ThreeCard tc[];
    int stt;
    public RoomView(User o, ClientControl cl, boolean c) {
        this.o = o;
        this.cl = cl;
        this.c = c;
        this.check = true;
        tc=new ThreeCard[4];
        sta1 = new Status[4];
        initComponents();
        if (!c) {
            jButton1.setVisible(false);
        }
        thread = new Thread(new Runnable() {
            @Override
            public void run() {

                while (true) {
                    serverSendObject sso = cl.receiveData();
                    ArrayList<Object> ao = sso.getList();

                    //System.out.println(d);
                    if (sso.getCommand() == Command.PLAY) {
                        //log()
                        Stringsend ob = (Stringsend) sso.getObject();
                        ArrayList<Status> as = new ArrayList<Status>();
                        for (int i = 0; i < ao.size(); i++) {
                            Status k = (Status) ao.get(i);
                            //logcon(k.toString2());
                            sta1[i] = k;
                            as.add(k);

                        }
                        s = ob.getK();
                        tc=ob.getTt();
                        showall(ob);

                    } else if (sso.getCommand() == Command.CONTINUE) {
                        check = false;
                        if (!sso.isCheck()) {
                            openSearch(c);
                        }

                    } else if (sso.getCommand() == Command.JOINTABLE) {
                        Stringsend ob = (Stringsend) sso.getObject();
                        ArrayList<Status> as = new ArrayList<Status>();
                        for (int i = 0; i < ao.size(); i++) {
                            Status k = (Status) ao.get(i);
                            //logcon(k.toString2());
                            sta1[i] = k;
                            as.add(k);

                        }
                        s = ob.getK();
                        showall(ob);
                    }
                }

            }

        });
        thread.start();

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ten2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Diem2 = new javax.swing.JLabel();
        Bai2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Ten3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Bai3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        Ten4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        bai4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        Ten1 = new javax.swing.JLabel();
        Diem1 = new javax.swing.JLabel();
        Bai1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Ten2.setForeground(new java.awt.Color(0, 0, 0));
        Ten2.setText("Nguyen Van Hieu");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/worker-1659453-1409975.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        Diem2.setText("Diem so ");

        Bai2.setText("Lá Bài");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ten2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Diem2)
                        .addGap(18, 18, 18)
                        .addComponent(Bai2)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ten2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Diem2)
                    .addComponent(Bai2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 240, 100));

        jPanel2.setBackground(new java.awt.Color(255, 51, 51));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/avatar-1659528-1410050.png"))); // NOI18N
        jLabel2.setText("Nguyen van tuan");

        Ten3.setForeground(new java.awt.Color(0, 51, 51));
        Ten3.setText("Tran Van Tiien");

        jLabel11.setText("Diem so ");

        Bai3.setText("Lá Bài:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ten3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(Bai3)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ten3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(Bai3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 240, 100));

        jPanel3.setBackground(new java.awt.Color(255, 102, 51));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setForeground(new java.awt.Color(255, 255, 51));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/avatar-1659503-1410025.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        Ten4.setForeground(new java.awt.Color(0, 51, 51));
        Ten4.setText("Nhu Tuan");

        jLabel10.setText("Diem so ");

        bai4.setText("Lá Bài:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ten4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(bai4)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 8, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ten4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(bai4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 110));

        jPanel4.setBackground(new java.awt.Color(0, 153, 153));
        jPanel4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/angry-1659533-1410055.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        Ten1.setForeground(new java.awt.Color(0, 0, 0));
        Ten1.setText("Nguyen Thu Thao");

        Diem1.setText("Diem so ");

        Bai1.setText("Lá Bài");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Diem1)
                        .addGap(18, 18, 18)
                        .addComponent(Bai1))
                    .addComponent(Ten1))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Ten1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Diem1)
                    .addComponent(Bai1))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 240, 100));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/royal-flush-playing-card-poker-table_23-2147881130.jpg"))); // NOI18N
        jLabel7.setText("chia bai");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 630, 450));

        jButton1.setText("Chia Bai");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 120, 160));

        jButton2.setText("return");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 360, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //showMessage("Bam nut");
        userSendObject uso = new userSendObject(Command.PLAY, true, o);
        cl.sendData(uso);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Searchview sea=new Searchview(o, cl);
        this.dispose();
        sea.setVisible(true);
        
    }//GEN-LAST:event_jButton2ActionPerformed
    private void showMessage(String msg) {
        JOptionPane.showMessageDialog(this, msg);

    }

    private boolean playagain(String s) {
        int click = JOptionPane.showConfirmDialog(null, s);
        if (click == JOptionPane.YES_OPTION) {

            return true;
        } else {
            return false;
        }
    }

    public void openSearch(boolean c) {

        Searchview rv = new Searchview(o, cl);
        rv.setVisible(true);
        this.dispose();
        thread.stop();

    }

    public void showall(Stringsend ob) {
        Ten1.setText(sta1[0].getName());
        Diem1.setText(sta1[0].getDiem() + "");
        //Bai1.setText(sta1[0].getAllnum());
        Bai1.setText(s[0]);
        Ten2.setText(sta1[1].getName());
        Diem2.setText(sta1[1].getDiem() + "");
        // Bai2.setText(sta1[1].getAllnum());
        Bai2.setText(s[1]);
        int term1 = 0;
        for(int i=0;i<sta1.length;i++){
            if(sta1[i].getName().equals(o.getUserName())){
               term1= tc[i].getTt();
               break;
            }
                
            
        }
        if (playagain("Chuc mung :"+o.getUserName()+",Ban duoc them "+term1)) {
            System.out.println(".run()" + check);
            if (check == false) {
                openSearch(c);

            }
        } else {
            if (check == false) {
                openSearch(c);
            } else {
                System.out.println(".run()" + check);
                userSendObject uso = new userSendObject(Command.CONTINUE, false, ob);
                cl.sendData(uso);
                openSearch(c);
            }

        }

    }

    public void setplayer1() {
        Ten1.setText(o.getUserName());
        Diem1.setText(o.getEmail() + "");
        //Bai1.setText(sta1[0].getAllnum());

    }

    public void setplayer2() {
        Ten1.setText(o.getUserName());
        Diem1.setText(o.getEmail() + "");
        //Bai1.setText(sta1[0].getAllnum());

    }

    public void setplayer3() {
        Ten1.setText(o.getUserName());
        Diem1.setText(o.getEmail() + "");
        //Bai1.setText(sta1[0].getAllnum());

    }

    public void setplayer4() {
        Ten1.setText(o.getUserName());
        Diem1.setText(o.getEmail() + "");
        //Bai1.setText(sta1[0].getAllnum());

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RoomView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new RoomView().setVisible(true);

            }
        });
    }
    
    private void log(String s) {
        JOptionPane.showConfirmDialog(null, s);
    }

    private void logcon(String toString2) {
        System.out.println(toString2);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bai1;
    private javax.swing.JLabel Bai2;
    private javax.swing.JLabel Bai3;
    private javax.swing.JLabel Diem1;
    private javax.swing.JLabel Diem2;
    private javax.swing.JLabel Ten1;
    private javax.swing.JLabel Ten2;
    private javax.swing.JLabel Ten3;
    private javax.swing.JLabel Ten4;
    private javax.swing.JLabel bai4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
